/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-31 07:03:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.travel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.vo.User;

public final class travelSelectArea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header-menu.jsp", Long.valueOf(1564556544945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');


User userLoggedIn = new User("abcde", "1234", "김지현", "F", null, null, null, null, null, "D", null, null, null, null, null);
//User userLoggedIn = null;


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<style>\n");
      out.write(".headerprofile-circle{\n");
      out.write("    border: 0px;\n");
      out.write("    border-radius: 100%;\n");
      out.write("}\n");
      out.write(".page-top{\n");
      out.write("\tmin-width: 1024px;\n");
      out.write("\tmin-height: 768px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("  <title>유람(가제)</title>\n");
      out.write("\n");
      out.write(" <!-- Bootstrap core CSS -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <!-- Bootstrap core JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Plugin JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Contact form JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for this template -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"page-top\">\n");
      out.write("  <!-- Navigation -->\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <a class=\"navbar-brand js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/\">유람(가제)</a>\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("        메뉴\n");
      out.write("        <i class=\"fas fa-bars\"></i>\n");
      out.write("      </button>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/travel/travelSelectArea\">여행지</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">여행이야기</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" id=\"separator\"> <span class=\"nav-link js-scroll-trigger\"></span>\n");
      out.write("           <!--  <a class=\"nav-link js-scroll-trigger\" href=\"#about\"></a> -->\n");
      out.write("          </li>\n");
      out.write("          ");
if(userLoggedIn==null){ 
      out.write("\n");
      out.write("\t          <li class=\"nav-item\">\n");
      out.write("\t            <a class=\"nav-link js-scroll-trigger\" href='");
      out.print(request.getContextPath() );
      out.write("/user/userLoginFrm'>로그인</a> <!-- userLogin.jsp로 이동하는 서블릿 -->\n");
      out.write("\t          </li> \n");
      out.write("\t\t      <li class=\"nav-item\">\n");
      out.write("\t\t        <a class=\"nav-link js-scroll-trigger\" href=\"#contact\">회원가입</a>\n");
      out.write("\t\t      </li>\n");
      out.write("          ");
 }
          	else if(userLoggedIn!=null){ 
      out.write("\n");
      out.write("          \t <li class=\"nav-item\">\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">로그아웃</a>\n");
      out.write("         \t</li>\n");
      out.write("          \t <li class=\"nav-item\">\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'>\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/profile.jpg\" class=\"headerprofile-circle\"  width=\"40\" height=\"40\" />\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\n");
      out.write("\t         </li> \n");
      out.write("         ");
 }
      out.write("\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for this template -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("   $('document').ready(function() {\r\n");
      out.write("   var area0 = [\"시/도 선택\",\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\"];\r\n");
      out.write("   var area1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("   var area2 = [\"계양구\",\"남구\",\"남동구\",\"동구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("   var area3 = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("   var area4 = [\"광산구\",\"남구\",\"동구\",\"북구\",\"서구\"];\r\n");
      out.write("   var area5 = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("   var area6 = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("   var area7 = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("   var area8 = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"여주군\",\"연천군\"];\r\n");
      out.write("   var area9 = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("   var area10 = [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\",\"청원군\"];\r\n");
      out.write("   var area11 = [\"계룡시\",\"공주시\",\"논산시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"당진군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("   var area12 = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("   var area13 = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("   var area14 = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("   var area15 = [\"거제시\",\"김해시\",\"마산시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"진해시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("   var area16 = [\"서귀포시\",\"제주시\",\"남제주군\",\"북제주군\"];\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택 박스 초기화\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").each(function() {\r\n");
      out.write("  $selsido = $(this);\r\n");
      out.write("  $.each(eval(area0), function() {\r\n");
      out.write("   $selsido.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("  });\r\n");
      out.write("  $selsido.next().append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" // 시/도 선택시 구/군 설정\r\n");
      out.write("\r\n");
      out.write(" $(\"select[name^=sido]\").change(function() {\r\n");
      out.write("  var area = \"area\"+$(\"option\",$(this)).index($(\"option:selected\",$(this))); // 선택지역의 구군 Array\r\n");
      out.write("  var $gugun = $(this).next(); // 선택영역 군구 객체\r\n");
      out.write("  $(\"option\",$gugun).remove(); // 구군 초기화\r\n");
      out.write("\r\n");
      out.write("  if(area == \"area0\")\r\n");
      out.write("   $gugun.append(\"<option value=''>구/군 선택</option>\");\r\n");
      out.write("  else {\r\n");
      out.write("   $.each(eval(area), function() {\r\n");
      out.write("    $gugun.append(\"<option value='\"+this+\"'>\"+this+\"</option>\");\r\n");
      out.write("   });\r\n");
      out.write("  }\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"masthead\" style=\"height:300px;\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"intro-text\" style=\"padding-top:140px; !important\">\r\n");
      out.write("        <div class=\"intro-heading text-uppercase\">\r\n");
      out.write("       \t\t\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/travel/travelView\" method=\"get\">\r\n");
      out.write("\t\t<select name=\"sido1\" id=\"sido1\"></select>\r\n");
      out.write("\t\t<select name=\"gugun1\" id=\"gugun1\"></select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"이동\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
