/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-07-30 12:45:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.vo.User;

public final class mypageView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header-menu.jsp", Long.valueOf(1564490699369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');


User userLoggedIn = new User("abcde", "1234", "김지현", "F", null, null, null, null, null, "D", null, null, null, null, null);
//User userLoggedIn = null;


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<style>\n");
      out.write(".headerprofile-circle{\n");
      out.write("    border: 0px;\n");
      out.write("    border-radius: 100%;\n");
      out.write("}\n");
      out.write(".page-top{\n");
      out.write("\tmin-width: 1024px;\n");
      out.write("\tmin-height: 768px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("  <title>유람(가제)</title>\n");
      out.write("\n");
      out.write(" <!-- Bootstrap core CSS -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <!-- Bootstrap core JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Plugin JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Contact form JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for this template -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"page-top\">\n");
      out.write("  <!-- Navigation -->\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <a class=\"navbar-brand js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/\">유람(가제)</a>\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("        메뉴\n");
      out.write("        <i class=\"fas fa-bars\"></i>\n");
      out.write("      </button>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/travel/travelSelectArea\">여행지</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">여행이야기</a>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" id=\"separator\"> <span class=\"nav-link js-scroll-trigger\"></span>\n");
      out.write("           <!--  <a class=\"nav-link js-scroll-trigger\" href=\"#about\"></a> -->\n");
      out.write("          </li>\n");
      out.write("          ");
if(userLoggedIn==null){ 
      out.write("\n");
      out.write("\t          <li class=\"nav-item\">\n");
      out.write("\t            <a class=\"nav-link js-scroll-trigger\" href='");
      out.print(request.getContextPath() );
      out.write("/user/userLoginFrm'>로그인</a> <!-- userLogin.jsp로 이동하는 서블릿 -->\n");
      out.write("\t          </li> \n");
      out.write("\t\t      <li class=\"nav-item\">\n");
      out.write("\t\t        <a class=\"nav-link js-scroll-trigger\" href=\"#contact\">회원가입</a>\n");
      out.write("\t\t      </li>\n");
      out.write("          ");
 }
          	else if(userLoggedIn!=null){ 
      out.write("\n");
      out.write("          \t <li class=\"nav-item\">\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">로그아웃</a>\n");
      out.write("         \t</li>\n");
      out.write("          \t <li class=\"nav-item\">\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'>\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/profile.jpg\" class=\"headerprofile-circle\"  width=\"40\" height=\"40\" />\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\n");
      out.write("\t         </li> \n");
      out.write("         ");
 }
      out.write("\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <!-- Bootstrap core CSS -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <!-- Bootstrap core JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Plugin JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Contact form JavaScript -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for this template -->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\n");
      out.write("  <style>\n");
      out.write("#profile-header{\n");
      out.write("\tpadding-bottom: 20px;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tbackground-color:#fed136;\n");
      out.write("} \n");
      out.write("  \n");
      out.write("#sideNav {\n");
      out.write("    text-align: center;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    display: -webkit-box;\n");
      out.write("    display: -ms-flexbox;\n");
      out.write("    display: fixed;\n");
      out.write("    -webkit-box-orient: vertical;\n");
      out.write("    -webkit-box-direction: normal;\n");
      out.write("    -ms-flex-direction: column;\n");
      out.write("    flex-direction: column;\n");
      out.write("    width: 22%;\n");
      out.write("\tmin-width: 250px;\n");
      out.write("    /*height: 100vh;*/\n");
      out.write("    background: #fed136; \n");
      out.write("    min-width: 250px;\n");
      out.write("}\n");
      out.write(".profile-circle{\n");
      out.write("\tmax-width: 10rem;\n");
      out.write("    max-height: 10rem;\n");
      out.write("    border: 0.5rem solid #212529;\n");
      out.write("    border-radius: 100%;\n");
      out.write("    min-width: 0;\n");
      out.write("    min-height: 0;\n");
      out.write("}\n");
      out.write("#sideNav .navbar-nav .nav-item .nav-link {\n");
      out.write("  font-weight: 800;\n");
      out.write("  letter-spacing: 0.05rem;\n");
      out.write("  text-transform: uppercase;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#sideNav .navbar-toggler:focus {\n");
      out.write("  outline-color: #d48a6e;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a .nav-link js-scroll-trigger{\n");
      out.write("\tcolor: #007bff;\n");
      out.write("    text-decoration: none;\n");
      out.write("    background-color: transparent;\n");
      out.write("\n");
      out.write("}\n");
      out.write("table{\n");
      out.write("\tmargin: 10 auto;\n");
      out.write("\tmargin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table tr :hover{\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tcolor: orangered;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("table td{\n");
      out.write("\tpadding: 10px;\n");
      out.write("\tborder-bottom: 1px solid #212529;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("    border-right: 0;\n");
      out.write("    border-left:0;\n");
      out.write("    height: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#sideNav, table {\n");
      out.write("\tfont-size: 90%;\n");
      out.write("    font-weight: 400;\n");
      out.write("   /* padding: .75em 0;*/\n");
      out.write("    letter-spacing: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div#profile-header{\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section#page-top{\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("article{\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop:0;\n");
      out.write("\tborder:1px solid;\n");
      out.write("\twidth: 52%;\n");
      out.write("\ttop:10px;\n");
      out.write("\tleft:23%;\n");
      out.write("\theight: 500px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("  \n");
      out.write(" <header class=\"masthead\" style=\"height:300px;\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"intro-text\" style=\"padding-top:140px; !important\">\n");
      out.write("        <div class=\"intro-heading text-uppercase\">\n");
      out.write("       \t\t마이페이지\n");
      out.write("        </div>\n");
      out.write("     </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("  \n");
      out.write("<section id=\"page-top\" style=\"padding:0px; !important;\">\n");
      out.write("  <nav id=\"sideNav\">\n");
      out.write("\t<div id=\"profile-header\">\n");
      out.write("      <img class=\"profile-circle\"  style=\"margin: 50px auto 12px;\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/profile.jpg\" alt=\"\">\n");
      out.write("      <p class=\"userprofile-userId\">@userId <button>edit</button></p>\n");
      out.write("      <p class=\"userIntroduce\" style=\"margin-bottom: 50px;\">안녕하세요. 저는 userId입니다. 좋아하는 여행지는 #서촌입니다.<button>edit</button></p>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("   <table id=\"tbl-usermenu0\">\n");
      out.write("   \t <tr>\n");
      out.write("   \t\t<td>회원정보수정</td>\n");
      out.write("   \t</tr>\n");
      out.write("\t<tr>\n");
      out.write("   \t\t<td>쪽지함</td>\n");
      out.write("   \t</tr>\n");
      out.write("   \t<table id=\"tbl-usermenu1\">\n");
      out.write("   \t\t<tr>\n");
      out.write("   \t\t\t<td>예약내역</td>\n");
      out.write("   \t\t</tr>\n");
      out.write("   \t\t<tr>\n");
      out.write("   \t\t\t<td>장바구니</td>\n");
      out.write("   \t\t</tr>\n");
      out.write("   \t\t<tr>\n");
      out.write("   \t\t\t<td>위시리스트</td>\n");
      out.write("   \t\t</tr>\n");
      out.write("   \t</table>\n");
      out.write("\t\n");
      out.write("    <table id=\"tbl-usermenu3\">\n");
      out.write("    <tr>\n");
      out.write("   \t\t<td>설정</td>\n");
      out.write("   \t</tr>\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("\t<table id=\"tbl-usermenu4\" style=\"margin-bottom:0px; !important\">\n");
      out.write("    <tr>\n");
      out.write("    \t<td>FAQ</td>\n");
      out.write("    </tr>\n");
      out.write("    \n");
      out.write("    <tr>\n");
      out.write("    \t<td>1:1문의</td>\n");
      out.write("    </tr>\n");
      out.write("    \n");
      out.write("    <tr>\n");
      out.write("    \t<td>공지사항</td>\n");
      out.write("    </tr> \t\n");
      out.write("\t</table>\n");
      out.write("  </nav>   \n");
      out.write("  \t<article class=\"myPost\">\n");
      out.write("  \t\n");
      out.write("\t</article> \n");
      out.write(" </section>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
