/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-19 21:29:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.story;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sns.model.vo.ProfileSNS;
import sns.model.vo.FollowSNS;
import java.util.List;
import sns.model.service.SNSService;
import user.model.service.UserService;
import sns.model.vo.ProfileSNS;
import user.model.vo.User;
import user.model.service.UserService;
import sns.model.vo.ProfileSNS;
import sns.model.service.SNSService;
import user.model.vo.User;

public final class storyMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header-menu.jsp", Long.valueOf(1566222456000L));
    _jspx_dependants.put("/WEB-INF/views/story/sidenav.jsp", Long.valueOf(1566250181000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("user.model.service.UserService");
    _jspx_imports_classes.add("sns.model.vo.ProfileSNS");
    _jspx_imports_classes.add("sns.model.vo.FollowSNS");
    _jspx_imports_classes.add("sns.model.service.SNSService");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write(" <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for this template -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\r\n");
      out.write("\r\n");


	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	System.out.println("userLoggedIn@userLogin.jsp=" + userLoggedIn);
	User loggedIn = null;
	if(userLoggedIn!=null){
		loggedIn = new UserService().selectOne(userLoggedIn.getUserId());
	}
	ProfileSNS profile = (ProfileSNS)request.getAttribute("profileSNS");

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <title>유람</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("header.masthead{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("background-image:");
      out.print(userLoggedIn!=null && profile!=null && profile.getHeaderRenamedFilename() != null?"url('"+request.getContextPath()+"/upload/profile/"+profile.getHeaderRenamedFilename()+"')":"url('"+request.getContextPath()+"/img/header-new.jpg');");
      out.write("\r\n");
      out.write("  \t\t\t\t/* 로그인한 상태이고 이 유저의 profile.getheaderimg가 널이 아닐때  유저가 바꾼 renamed헤더 이미지로 바꾸고 싶음!  */\t\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".header-profile-circle{\r\n");
      out.write("    border: 0px;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-menu-container{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/\">유람</a>\r\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        Menu\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/travel/travelSelectArea\">여행지</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t  ");
 if(userLoggedIn!=null){
      out.write("\r\n");
      out.write("\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=");
      out.print(userLoggedIn.getUserId() );
      out.write("\">여행이야기</a>\r\n");
      out.write("\t      ");
} else{ 
      out.write("\r\n");
      out.write("\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">여행이야기</a>\r\n");
      out.write("\t      ");
} 
      out.write("\r\n");
      out.write("\t      \r\n");
      out.write("\t      </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <span class=\"nav-link js-scroll-trigger\">&nbsp;&nbsp;</span>\r\n");
      out.write("          </li>\r\n");
      out.write("         ");
if(userLoggedIn==null){ 
      out.write("\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link js-scroll-trigger\" href='");
      out.print(request.getContextPath() );
      out.write("/user/userLoginFrm'>로그인</a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t          </li> \r\n");
      out.write("\t\t      <li class=\"nav-item\">\r\n");
      out.write("\t\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userEnrollFrm\">회원가입</a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("         ");
 }
          	else if(userLoggedIn!=null && "A".equals(userLoggedIn.getUserType())){
      out.write("\r\n");
      out.write("          \t<li class=\"nav-item\">\r\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/user/userLogout\">로그아웃</a>\r\n");
      out.write("         \t</li>\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/admin/adminView'>\r\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/profile/");
      out.print(loggedIn.getFileName() );
      out.write("\" class=\"header-profile-circle\"  width=\"40\" height=\"40\" />\r\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t         </li> \r\n");
      out.write("          ");
 }
          	else if(userLoggedIn!=null){ 
      out.write("\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/user/userLogout\">로그아웃</a>\r\n");
      out.write("         \t</li>\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'>\r\n");
      out.write("\t           \t");
if(userLoggedIn==null || userLoggedIn.getFileName()==null){
      out.write("\r\n");
      out.write("\t           \t\t<button onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'\"></button>\r\n");
      out.write("\t           \t");
 } else if(userLoggedIn!=null && loggedIn!=null) {
      out.write("\r\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/profile/");
      out.print(loggedIn.getFileName() );
      out.write("\" class=\"header-profile-circle\"  width=\"40\" height=\"40\" />\r\n");
      out.write("\t           \t");
} 
      out.write("\r\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t         </li> \r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  ");
      out.write("  \r\n");
      out.write(" \r\n");

	String mypage = request.getParameter("mypage");
	User mypageUser = new UserService().selectOne(mypage);
 	ProfileSNS profileSNS = (ProfileSNS)request.getAttribute("profileSNS");
 	userLoggedIn = (User)session.getAttribute("userLoggedIn");
	List<String> blockLoggedInList = new SNSService().selectOneIdBlock(userLoggedIn.getUserId());
 	List<String> followLoggedInList = new SNSService().selectOneIdFollow(userLoggedIn.getUserId());
 
	


      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function updateHeaderText(){\r\n");
      out.write("\tvar headertext = $(\"#headerBefore\").text();\r\n");
      out.write("\t\r\n");
      out.write("\tvar html = \"<input type='text' id='headerAfter' name='headerAfter' value='\"+headertext+\"'/ size='20'>\";\r\n");
      out.write("\thtml += \"<button id='headerAfterBtn' class='btn btn-light' onclick='headerTextModify();' style='margin-left:10px; width:60px;'>edit</button>\"\r\n");
      out.write("\t$(\"#headerBeforeBtn\").remove();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#headerFrm\").html(html);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateNickName(){\r\n");
      out.write("\tvar nickname = $(\"#nickBefore\").text();\r\n");
      out.write("\t\r\n");
      out.write("\tvar html = \"<input type='text' id='nickAfter' name='nickafter' value='\"+nickname+\"' size='10' />\";\r\n");
      out.write("\thtml += \"<button id='nickAfterBtn'class='btn btn-light' onclick='nickNameModify();' style='margin-left:10px; width:60px;'>edit</button>\"\r\n");
      out.write("\t$(\"#nickBeforeBtn\").remove();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#nickFrm\").html(html);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updateIntroduce(){\r\n");
      out.write("\tvar intro = $(\"#introBefore\").text();\r\n");
      out.write("\t\r\n");
      out.write("\tvar html = \"<textarea name='introAfter' id='introAfter' cols='20' rows='4'>\"+intro+\"</textarea>\";\r\n");
      out.write("\thtml += \"<button id='introAfterBtn' class='btn btn-light' onclick='introModify();' style='float:right; margin-right: 14px; width:60px;'>edit</button>\"\r\n");
      out.write("\t$(\"#introBeforeBtn\").remove();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#introFrm\").html(html);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function headerTextModify(){\r\n");
      out.write("\tvar headertext = $(\"#headerAfter\").val();\r\n");
      out.write("\r\n");
      out.write("\tif(headertext.length==0){\r\n");
      out.write("\t\talert('내용을 입력해주세요.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(headertext.length>20){\r\n");
      out.write("\t\talert('최대 20글자까지 가능합니다.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar userid = '");
      out.print(userLoggedIn.getUserId() );
      out.write("';\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\theadertext : headertext,\r\n");
      out.write("\t\t\tuserid : userid\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#headerAfter\").remove();\r\n");
      out.write("\t$(\"#headerAfterBtn\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/gson/sns/headerTextModify.do\",\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar html = \"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=");
      out.print(mypage );
      out.write("' style='color:white' id='headerBefore'>\"+headertext+\"</a>\";\r\n");
      out.write("\t\t\thtml+=\"&nbsp;<button id='headerBeforeBtn' class='btn btn-light' style='width:60px;' onclick='updateHeaderText();'>edit</button>\";\r\n");
      out.write("\t\t\t$(\"#headerFrm\").html(html);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function nickNameModify(){\r\n");
      out.write("\tvar nickname = $(\"#nickAfter\").val();\r\n");
      out.write("\r\n");
      out.write("\tif(nickname.length==0){\r\n");
      out.write("\t\talert('닉네임을 입력해주세요.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(nickname.length>8){\r\n");
      out.write("\t\talert('최대 8글자까지 가능합니다.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar userid = '");
      out.print(userLoggedIn.getUserId() );
      out.write("';\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tnickname : nickname,\r\n");
      out.write("\t\t\tuserid : userid\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#nickAfter\").remove();\r\n");
      out.write("\t$(\"#nickAfterBtn\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/gson/sns/nickNameModify.do\",\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar html = \"<span id='nickBefore'>\"+nickname+\"</span>\";\r\n");
      out.write("\t\t\thtml+=\"<button id='nickBeforeBtn' class='btn btn-light' onclick='updateNickName();' style='width:60px;'>edit</button>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#nickFrm\").html(html);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function introModify(){\r\n");
      out.write("\tvar intro = $(\"#introAfter\").val();\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(intro.length==0){\r\n");
      out.write("\t\talert('소개를 입력해주세요.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tif(intro.length>20){\r\n");
      out.write("\t\talert('최대 20글자까지 가능합니다.');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar userid = '");
      out.print(userLoggedIn.getUserId() );
      out.write("';\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tintro : intro,\r\n");
      out.write("\t\t\tuserid : userid\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#introAfter\").remove();\r\n");
      out.write("\t$(\"#introAfterBtn\").remove();\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/gson/sns/introModify.do\",\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\ttype : \"post\",\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tvar html = \"<span id='introBefore'>\"+intro+\"</span>\";\r\n");
      out.write("\t\t\thtml+=\"<button id='introBeforeBtn' class='btn btn-light' style='width:60px;' onclick='updateIntroduce();'>edit</button>\";\r\n");
      out.write("\t\t\t$(\"#introFrm\").html(html);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function follow(){\r\n");
      out.write("\tvar param={\r\n");
      out.write("\t\t\tuserFollowing : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\r\n");
      out.write("\t\t\tuserFollowed : '");
      out.print(mypageUser.getUserId() );
      out.write("'    \t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/follow.do',\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tif($('.followerTr').length>0){\r\n");
      out.write("\t\t\t\t\t\t$('.followerTr').remove();\r\n");
      out.write("\t\t\t\t\t\t$('.follower').remove();\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar html = \"<tr class='followerTr'><td class='follower'>팔로워</td></tr>\";\r\n");
      out.write("\t\t\t\t\t$(\"#tbl-followmenu\").append(html);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\".follower\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\t \t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/follower.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:\"mypage=\"+'");
      out.print(mypage);
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax처리성공!\");\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"complete!!!\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t \t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").removeClass(\"btn-success\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").addClass(\"btn-danger\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").html(\"Unfollow\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").off('click')\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").on('click', unfollow);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.blackArea').html('');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#follower\").on(\"click\", function(){\r\n");
      out.write("\t\t\t\t \t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/follower.jsp\",\r\n");
      out.write("\t\t\t\t\t\t\tdata:\"mypage=\"+'");
      out.print(mypage);
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax처리성공!\");\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(\"complete!!!\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t \t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t,\r\n");
      out.write("\t\t\terror : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unfollow(){\r\n");
      out.write("\t\tvar param={\r\n");
      out.write("\t\t\tuserFollowing : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\r\n");
      out.write("\t\t\tuserFollowed : '");
      out.print(mypageUser.getUserId() );
      out.write("'    \t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/unFollow.do',\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tsuccess : function(data){\t\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").removeClass(\"btn-danger\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").addClass(\"btn-success\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").html(\"Follow\");\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").off('click');\r\n");
      out.write("\t\t\t\t\t$(\"#followBtn\").on('click', follow);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.followerTr').remove();\r\n");
      out.write("\t\t\t\t\t$('.follower').remove();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('.blackArea').html(\"<button type='button' class='btn btn-dark' id='blockBtn' onclick='block();'>Block</button>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($('#follower-container').length>0){\r\n");
      out.write("\t\t\t\t\t\tlocation.href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=");
      out.print(mypage );
      out.write("';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}) \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function block(){\r\n");
      out.write("\tvar param={\r\n");
      out.write("\t\tuserBlocking : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\r\n");
      out.write("\t\tuserBlocked : '");
      out.print(mypageUser.getUserId() );
      out.write("'    \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/block.do',\r\n");
      out.write("\t\tdata : param,\r\n");
      out.write("\t\tdataType: 'json',\r\n");
      out.write("\t\ttype : 'post',\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t$(\"#followBtn\").remove();\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").removeClass(\"btn-dark\");\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").addClass(\"btn-light\");\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").text(\"Unblock\");\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").css(\"width\", \"105px\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").off(\"click\");\r\n");
      out.write("\t\t\t\t$(\"#blockBtn\").on(\"click\", unblock);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}) \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unblock(){\r\n");
      out.write("\tvar param={\r\n");
      out.write("\t\t\tuserBlocking : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\r\n");
      out.write("\t\t\tuserBlocked : '");
      out.print(mypageUser.getUserId() );
      out.write("'    \t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/unblock.do',\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\ttype : 'post',\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t$(\".greenArea\").append(\"<button type='button' class='btn btn-success' id='followBtn' onclick='follow();'>Follow</button>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").removeClass(\"btn-light\");\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").addClass(\"btn-dark\");\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").text(\"block\");\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").css(\"width\", \"81.36px\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").off(\"click\");\r\n");
      out.write("\t\t\t\t\t$(\"#blockBtn\").on(\"click\", block);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}) \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write(" <header class=\"masthead\" style=\"height:300px;\">\r\n");
      out.write("      <div class=\"intro-text\" style=\"padding-top:140px; !important\">\r\n");
      out.write("        <div class=\"intro-heading text-uppercase\">\r\n");
      out.write("       \t\t<div id=\"headerFrm\">\r\n");
      out.write("\t\t\t\t<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=");
      out.print(mypage );
      out.write("' style='color:white' id=\"headerBefore\">");
      out.print(profileSNS.getHeaderText()!=null? profileSNS.getHeaderText() : profileSNS.getProfileUserNickname()+"의 홈" );
      out.write("</a>\r\n");
      out.write("\t\t\t\t");
if(userLoggedIn!=null && mypage.equals(userLoggedIn.getUserId())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id=\"headerBeforeBtn\" onclick=\"updateHeaderText();\" style='margin-left:10px;' class=\"btn btn-light\">edit</button>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("  </header>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <form action=\"\" name=\"memomsgFrm\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"userId\" />\r\n");
      out.write("</form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<section class=\"page-top\" style=\"padding:0px;\">\r\n");
      out.write("\t  <nav id=\"sideNav\">\r\n");
      out.write("\t\t<div id=\"profile-header\">\r\n");
      out.write("\t      <img class=\"profile-circle\"  style=\"margin: 50px auto 12px;\" src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/profile/");
      out.print(mypageUser.getFileName());
      out.write("\" alt=\"\">\r\n");
      out.write("\t      <div id=\"nickFrm\">\r\n");
      out.write("\t      \t<span id=\"nickBefore\" style=\"font-weight: 700;\">");
      out.print(profileSNS.getProfileUserNickname() );
      out.write("</span>\r\n");
      out.write("\t      \t");
if(userLoggedIn!=null && mypage.equals(userLoggedIn.getUserId())) { 
      out.write("\r\n");
      out.write("\t      \t\t<button id=\"nickBeforeBtn\" onclick=\"updateNickName();\" class=\"btn btn-light\">edit</button>\r\n");
      out.write("\t      \t");
}
      out.write("\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div id=\"introFrm\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t<span id=\"introBefore\">");
      out.print(profileSNS.getProfileUserIntroduce()!=null? profileSNS.getProfileUserIntroduce(): "안녕하세요. 저는 " + profileSNS.getProfileUserNickname() +"입니다." );
      out.write("</span>\r\n");
      out.write("\t\t\t");
if(userLoggedIn!=null && mypage.equals(userLoggedIn.getUserId())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<button id=\"introBeforeBtn\" onclick=\"updateIntroduce();\" class=\"btn btn-light\">edit</button>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t \t\t</div>\r\n");
      out.write("\t \r\n");
      out.write("\t      \t");
 if(userLoggedIn!=null && !mypage.equals(userLoggedIn.getUserId())){
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if(followLoggedInList.contains(mypage)){	
      out.write("\r\n");
      out.write("\t\t\t\t\t\t <div class='greenArea'><button type=\"button\" class=\"btn btn-danger\" id=\"followBtn\" onclick=\"unfollow();\">Unfollow</button></div>\r\n");
      out.write("\t\t\t\t\t\t <div class='blackArea'></div>\r\n");
      out.write("\t\t\t\t\t");
} else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
if(blockLoggedInList.contains(mypage)){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='greenArea'></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='blackArea'><button type=\"button\" id=\"blockBtn\" class=\"btn btn-light\" onclick=\"unblock();\">Unblock</button></div>\r\n");
      out.write("\t\t\t\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class='greenArea'><button type=\"button\" class=\"btn btn-success\" id=\"followBtn\" onclick=\"follow();\">Follow</button></div>\r\n");
      out.write("\t\t\t\t\t\t<div class='blackArea'><button type=\"button\" id=\"blockBtn\" class=\"btn btn-dark\" onclick=\"block();\">Block</button></div>\r\n");
      out.write("\t\t\t\t\t");
 }
					}
			} 
      out.write("\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t    <table class=\"tbl-usermenu\">\r\n");
      out.write("\t   \t\t<tr>\r\n");
      out.write("\t  \t\t\t<td id=\"gohome\">홈</td>\r\n");
      out.write("\t   \t\t</tr>\r\n");
      out.write("\t   \t</table>\r\n");
      out.write("\t   \t<table class=\"tbl-usermenu\" id=\"tbl-followmenu\">\r\n");
      out.write("   \t \t\t");
if(userLoggedIn!=null && userLoggedIn.getUserId().equals(mypage)) {
      out.write("\r\n");
      out.write("\t\t   \t\t<tr>\r\n");
      out.write("\t\t   \t\t\t<td id=\"gomsg\">메시지</td>\r\n");
      out.write("\t\t   \t\t</tr>\r\n");
      out.write("\t   \t\t");
} 
      out.write("\r\n");
      out.write("\t   \t\t\r\n");
      out.write("\t   \t\t");
if((userLoggedIn!=null && mypage.equals(userLoggedIn.getUserId())) ||  !mypage.equals(userLoggedIn.getUserId()) && followLoggedInList.contains(mypage)){
      out.write("\r\n");
      out.write("\t\t   \t\t<tr class=\"followerTr\">\r\n");
      out.write("\t\t   \t\t\t<td class=\"follower\">팔로워</td>\r\n");
      out.write("\t\t   \t\t</tr>\r\n");
      out.write("\t\t\t");
 }
      out.write("\r\n");
      out.write("\t   \t</table>\r\n");
      out.write("\t   \t");
if(userLoggedIn!=null && userLoggedIn.getUserId().equals(mypage)) {
      out.write("\r\n");
      out.write("\t    <table class=\"tbl-usermenu\">\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t   \t\t<td id=\"setting\">설정</td>\r\n");
      out.write("\t   \t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t<table class=\"tbl-usermenu\" style=\"margin-bottom:0px; !important\">\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t    \t<td>FAQ</td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t    \t<td id=\"QuestionList\">1:1문의</td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t   \t\r\n");
      out.write("\t  </nav>\r\n");
      out.write("\t  \r\n");
      out.write(" <style>\t \r\n");
      out.write(".page-top{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#profile-header{\r\n");
      out.write("\tpadding-bottom: 40px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tbackground-color:");
      out.print(profileSNS.getThemeColor()!=null? profileSNS.getThemeColor() : "#fed136" );
      out.write(";\r\n");
      out.write("} \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("#sideNav {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    /*display: fixed;*/\r\n");
      out.write("    -webkit-box-orient: vertical;\r\n");
      out.write("    -webkit-box-direction: normal;\r\n");
      out.write("    -ms-flex-direction: column;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 210px;\r\n");
      out.write("    /*height: 100vh;*/\r\n");
      out.write("    background:");
      out.print(profileSNS.getThemeColor()!=null? profileSNS.getThemeColor() : "#fed136" );
      out.write("; \r\n");
      out.write("    /*min-width: 250px;*/\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".profile-circle{\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    border: 0.5rem solid #212529;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blackArea, .greenArea {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#sideNav .navbar-nav .nav-item .nav-link {\r\n");
      out.write("  font-weight: 800;\r\n");
      out.write("  letter-spacing: 0.05rem;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sideNav .navbar-toggler:focus {\r\n");
      out.write("  outline-color: #d48a6e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a .nav-link js-scroll-trigger{\r\n");
      out.write("\tcolor: #007bff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".tbl-usermenu{\r\n");
      out.write("\tmargin: 10px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl-usermenu tr :hover{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tcolor: orangered;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl-usermenu td{\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tborder-bottom: 1px solid #212529;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("    border-right: 0;\r\n");
      out.write("    border-left:0;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sideNav, table {\r\n");
      out.write("\tfont-size: 90%;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("   /* padding: .75em 0;*/\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#profile-header{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-section{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    display: -webkit-box;\r\n");
      out.write("    display: -ms-flexbox;\r\n");
      out.write("    display: fixed;\r\n");
      out.write("    -webkit-box-orient: vertical;\r\n");
      out.write("    -webkit-box-direction: normal;\r\n");
      out.write("    -ms-flex-direction: column;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    width: 56%;\r\n");
      out.write("    /*height: 100vh;*/\r\n");
      out.write("    background: lightgray;\r\n");
      out.write("\r\n");
      out.write("    /*min-width: 800px;*/\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#timline-sns{\r\n");
      out.write("\tborder:1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#timeline-board-sns{\r\n");
      out.write("\tborder:1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".timeline-boardcontent-sns{\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\twidth: 580px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#boardcontent_img{\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl-usermenu td{\r\n");
      out.write("\twidth: 210px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nick_sns{\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write(".btn-dark,{\r\n");
      out.write("\twidth:81.36px;\r\n");
      out.write("}\r\n");
      out.write(".btn-light{\r\n");
      out.write("\twidth:105px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#headerBeforeBtn, #nickBeforeBtn, #introBeforeBtn{\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("var param = {\r\n");
      out.write("mypage : '");
      out.print(mypage);
      out.write("'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\t \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/home.jsp\",\r\n");
      out.write("\t\t\t\t\tdata:param,\r\n");
      out.write("\t\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"complete!!!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write(" \t$(\"#gohome\").on(\"click\", function(){\r\n");
      out.write(" \t\tvar param = {\r\n");
      out.write(" \t\t\t\t mypage : '");
      out.print(mypage);
      out.write("'\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\t$.ajax({\t \r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/home.jsp\",\r\n");
      out.write(" \t\t\t\tdata:param,\r\n");
      out.write(" \t\t\t\tsuccess: function(data){\r\n");
      out.write(" \t\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write(" \t\t\t\t},\r\n");
      out.write(" \t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write(" \t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write(" \t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write(" \t\t\t\t},\r\n");
      out.write(" \t\t\t\tcomplete: function(){\r\n");
      out.write(" \t\t\t\t\tconsole.log(\"complete!!!\");\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t});\r\n");
      out.write(" \t});\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write(" \t$(\".follower\").on(\"click\", function(){\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tvar param = {\r\n");
      out.write(" \t\t\t\tmypage : '");
      out.print(mypage );
      out.write("'\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t \t\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/follower.jsp\",\r\n");
      out.write("\t\t\tdata:param,\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리성공!\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\tconsole.log(\"complete!!!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write(" \t});\r\n");
      out.write(" \t\r\n");
      out.write(" \t$(\"#setting\").on(\"click\", function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/ajax/setting.jsp\", \r\n");
      out.write("\t\t\ttype: \"get\",\r\n");
      out.write("\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\"#container-sns\").html(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"#QuestionList\").on(\"click\", function(){\r\n");
      out.write("\t\tvar userId = '");
      out.print(userLoggedIn.getUserId() );
      out.write("';\t\r\n");
      out.write("\t\tconsole.log(\"userLoggedIn\"+userId);\r\n");
      out.write("\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/boardquestion/boardList?userId=\"+userId; \r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#gomsg\").on(\"click\", function(){\r\n");
      out.write("\t\t\tvar userId = '");
      out.print(userLoggedIn.getUserId() );
      out.write("';\t\r\n");
      out.write("\t\t\tconsole.log(\"userLoggedIn\"+userId);\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\r\n");
      out.write(" \t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/chat/chatroom.do?userId=\"+userId;\r\n");
      out.write(" \t\t\tvar title=\"popup\"; \r\n");
      out.write(" \t\t\tvar status = \"width=600px, height=400px, left=150px, top=0px\";\r\n");
      out.write(" \t\t\tvar popup = open(\"\", title, status);\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tvar frm = document.memomsgFrm;\r\n");
      out.write(" \t\t\tfrm.userId.value= userId;\r\n");
      out.write(" \t\t\tfrm.action = url;\r\n");
      out.write(" \t\t\tfrm.target=title;\r\n");
      out.write(" \t\t\tfrm.method= \"post\"; \r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t});\r\n");
      out.write("</script>\r\n");
      out.write("\t  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write(" <link href=\"/trav/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"/trav/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"/trav/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"/trav/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/trav/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"/trav/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"/trav/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"/trav/js/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for this template -->\r\n");
      out.write("  <script src=\"/trav/js/agency.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("   <div id=\"container-sns\"></div>\r\n");
      out.write("\t  \r\n");
      out.write(" </section>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
