/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-18 19:14:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sns.model.service.SNSService;
import user.model.service.UserService;
import user.model.vo.User;
import sns.model.vo.ProfileSNS;
import java.util.List;

public final class follower_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("user.model.service.UserService");
    _jspx_imports_classes.add("sns.model.service.SNSService");
    _jspx_imports_classes.add("user.model.vo.User");
    _jspx_imports_classes.add("sns.model.vo.ProfileSNS");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String mypage = request.getParameter("mypage");
    User userLoggedIn = (User)session.getAttribute("userLoggedIn");
    User mypageUser = new UserService().selectOne(mypage);
    
    List<String> followLoggedInList = new SNSService().selectOneIdFollow(userLoggedIn.getUserId());
    List<String> blockLoggedInList = new SNSService().selectOneIdBlock(userLoggedIn.getUserId());
    List<String> blockedLoggedInList = new SNSService().selectOneIdBlocked(userLoggedIn.getUserId());
    

      out.write("\n");
      out.write("<style>\n");
      out.write("#followerSearch {\n");
      out.write("\twidth:540px;\n");
      out.write("\tmargin:0 auto;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tfloat:left;\n");
      out.write("\ttext-align:left;\n");
      out.write("\tleft:10px;\n");
      out.write("\ttransition: 0.5s;\n");
      out.write("\ttop:10px;\n");
      out.write("}\n");
      out.write("#follower-container {\n");
      out.write("\twidth:540px;\n");
      out.write("\tmargin:0 auto;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tleft:220px;\n");
      out.write("\ttransition: 0.5s;\n");
      out.write("\ttop:30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#follower-container .tab {\n");
      out.write("\tlist-style: none;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tpadding: 0;\n");
      out.write("\toverflow: hidden;\n");
      out.write("}\n");
      out.write("/* Float the list items side by side */\n");
      out.write("#follower-container .tab li {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 33.3333%;\n");
      out.write("\tborder-bottom: 1px solid;\n");
      out.write("}\n");
      out.write("/* Style the links inside the list items */\n");
      out.write("#follower-container .tab li a {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tcolor: #000;\n");
      out.write("\ttext-align: center;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tpadding: 14px 16px;\n");
      out.write("\tfont-size: 17px;\n");
      out.write("\ttransition:0.3s;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("/* Style the tab content */\n");
      out.write("#follower-container .tabcontent {\n");
      out.write("\tdisplay: none;\n");
      out.write("\tbackground-color:black;\n");
      out.write("\tpadding: 6px 5px;\n");
      out.write("\tcolor:#fff;\n");
      out.write("}\n");
      out.write("#follower-container ul.tab li.current{\n");
      out.write("\tbackground-color: #fed136;\n");
      out.write("\tcolor: #222;\n");
      out.write("\tborder:1px solid;\n");
      out.write("\tborder-bottom: 0;\n");
      out.write("}\n");
      out.write("#follower-container .tabcontent.current {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tbackground: white;\n");
      out.write("\tcolor: black;\n");
      out.write("\tborder: 1px solid;\n");
      out.write("\tborder-top: 0px;\n");
      out.write("\tborder-collapse: collapse;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("div.followListContainer{\n");
      out.write("\tmargin:0 auto;\n");
      out.write("}\n");
      out.write("table.followList{\n");
      out.write("\twidth: 527px;\n");
      out.write("\tborder:1px solid black;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("table.followList td{\n");
      out.write("\twidth: 527px;\n");
      out.write("\tpadding: 8px;\n");
      out.write("}\n");
      out.write(".followerSearch{\n");
      out.write("\twidth: 200px;\n");
      out.write("\tfloat:left;\n");
      out.write("margin-bottom: 10px\n");
      out.write("}\n");
      out.write("\n");
      out.write(".firstRow{\n");
      out.write("\tmargin-left: 5px;\n");
      out.write("\tcolor: gray;\n");
      out.write("\tfloat: left;\n");
      out.write("\tdiplay:inline;\n");
      out.write("\tfont-size:0.8em;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".firstRow .followerURL{\n");
      out.write("\tfont-weight: 700;\n");
      out.write("\tfont-size: 1.2em;\n");
      out.write("\tcolor: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".ub-btns{\n");
      out.write("\tdisplay:inline;\n");
      out.write("\tfloat:right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".magni{\n");
      out.write("\tfloat:left;\n");
      out.write("\tmargin: 4px 3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header-profile-circle{\n");
      out.write("\tmargin-right: 5px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var followLoggedInList = new Array();\n");
      out.write("var blockLoggedInList = new Array();\n");
      out.write("var blockedLoggedInList = new Array();\n");
      out.write("\n");
      out.write("\n");
      out.write("console.log(followLoggedInList);\n");
      out.write("console.log(blockLoggedInList);\n");
      out.write("console.log(blockedLoggedInList);\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(()=>{\n");
      out.write("\t\n");
      out.write("\t");
if(followLoggedInList!=null){
      out.write('\n');
      out.write('	');
for(String id : followLoggedInList){
      out.write("\n");
      out.write("\tfollowLoggedInList .push('");
      out.print(id);
      out.write("');\n");
      out.write("\t");
} }
      out.write('\n');
      out.write('	');
if(blockLoggedInList!=null){
      out.write('\n');
      out.write('	');
for(String id : blockLoggedInList){
      out.write("\n");
      out.write("\tblockLoggedInList.push('");
      out.print(id);
      out.write("');\n");
      out.write("\t");
} }
      out.write('\n');
      out.write('	');
if(blockedLoggedInList!=null){
      out.write('\n');
      out.write('	');
for(String id : blockedLoggedInList){
      out.write("\n");
      out.write("\tblockedLoggedInList.push('");
      out.print(id);
      out.write("');\n");
      out.write("\t");
} }
      out.write("\n");
      out.write("\t\n");
      out.write("\tconsole.log(followLoggedInList);\n");
      out.write("\tconsole.log(blockLoggedInList);\n");
      out.write("\tconsole.log(blockedLoggedInList);\n");
      out.write("\t\n");
      out.write("\tvar param = {\n");
      out.write("\t\t\tmypage : '");
      out.print(mypage);
      out.write("'\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl:\"");
      out.print(request.getContextPath() );
      out.write("/gson/sns/followerOneList.do\",\n");
      out.write("\t\ttype:\"get\",\n");
      out.write("\t\tdata:param,\n");
      out.write("\t\tdataType:\"json\",\n");
      out.write("\t\tsuccess: function(data){\n");
      out.write("\t\t\t$(data).each((i,u)=>{\n");
      out.write("\t\t\t\tvar html = '';\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\thtml+=\"<div class='firstRow'>\";\n");
      out.write("\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/upload/profile/\"+u.profileRenamedFilename+\"' class='header-profile-circle'  width='40' height='40' />\";\n");
      out.write("\t\t\t\thtml+=\"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+u.profileUserId+\"' class='followerURL'>\"+u.profileUserNickname+\"</a>\";\n");
      out.write("\t\t\t\tif(u.profileUserType=='S'){\n");
      out.write("\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/img/checkmark.png' alt='''  width='20' height='20'  />\";\n");
      out.write("\t\t\t\t}\t\t\n");
      out.write("\t\t\t\thtml+=\"&nbsp;<span class='followerIntro'>@\"+u.profileUserId+\"</span>\";\n");
      out.write("\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\thtml+=\"<div class='ub-btns'>\"\n");
      out.write("\t\t\t\t\tif(u.profileUserId != '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\tif(followLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-danger' class='followerBtn' style='margin-right:2px;' value='\"+u.profileUserId+\"' onclick='unfollower(this);'>Unfollow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'></div>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\telse if(blockLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("' == '");
      out.print(mypage );
      out.write("' || blockedLoggedInList.includes(u.profileUserId)) return;\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'></div>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' value='\"+u.profileUserId+\"' class='btn btn-light' onclick='unblocker(this);''>Unblock</button></div>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\telse {\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-success' value='\"+u.profileUserId+\"' onclick='follower(this);'>Follow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' class='btn btn-dark' value='\"+u.profileUserId+\"' onclick='blocker(this);'>Block</button></div>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}else if(u.profileUserId == '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\thtml+=\"</div>\";\t\n");
      out.write("\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(\"#followerList\").append(html);\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(function() {\n");
      out.write("\t$('ul.tab li').click(function() {\t\n");
      out.write("\t\tvar activeTab = $(this).attr('data-tab');\n");
      out.write("\t\t$('ul.tab li').removeClass('current');\n");
      out.write("\t\t$('.tabcontent').removeClass('current');\n");
      out.write("\t\t$(this).addClass('current');\n");
      out.write("\t\t$('#' + activeTab).addClass('current');\n");
      out.write("\t\t\n");
      out.write("\t\tif($(this).attr('data-tab')=='tab1'){\n");
      out.write("\t\t\tvar param = {\n");
      out.write("\t\t\t\t\tmypage : '");
      out.print(mypage);
      out.write("'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"");
      out.print(request.getContextPath() );
      out.write("/gson/sns/followerOneList.do\",\n");
      out.write("\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\tdata:param,\n");
      out.write("\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(\"#followerList\").html('');\n");
      out.write("\t\t\t\t\t$(data).each((i,u)=>{\n");
      out.write("\t\t\t\t\t\tvar html = '';\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<div class='firstRow'>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/upload/profile/\"+u.profileRenamedFilename+\"' class='header-profile-circle'  width='40' height='40' />\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+u.profileUserId+\"' class='followerURL'>\"+u.profileUserNickname+\"</a>\";\n");
      out.write("\t\t\t\t\t\tif(u.profileUserType=='S'){\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/img/checkmark.png' alt='''  width='20' height='20'  />\";\n");
      out.write("\t\t\t\t\t\t}\t\t\n");
      out.write("\t\t\t\t\t\thtml+=\"&nbsp;<span class='followerId'>@\"+u.profileUserId+\"</span>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\thtml+=\"<div class='ub-btns'>\"\n");
      out.write("\t\t\t\t\t\t\tif(u.profileUserId != '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\tif(followLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-danger' class='followerBtn' style='margin-right:2px;' value='\"+u.profileUserId+\"' onclick='unfollower(this);'>Unfollow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse if(blockLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("' == '");
      out.print(mypage );
      out.write("' || blockedLoggedInList.includes(u.profileUserId)) return;\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' value='\"+u.profileUserId+\"' class='btn btn-light' onclick='unblocker(this);''>Unblock</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse {\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-success' value='\"+u.profileUserId+\"' onclick='follower(this);'>Follow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' class='btn btn-dark' value='\"+u.profileUserId+\"' onclick='blocker(this);'>Block</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}else if(u.profileUserId == '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\thtml+=\"</div>\";\t\n");
      out.write("\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$(\"#followerList\").append(html);\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t} \n");
      out.write("\t\t\n");
      out.write("\t\telse if($(this).attr('data-tab')=='tab2'){\n");
      out.write("\t\t\tvar param = {\n");
      out.write("\t\t\t\t\tmypage : '");
      out.print(mypage);
      out.write("'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"");
      out.print(request.getContextPath() );
      out.write("/gson/sns/followOneList.do\",\n");
      out.write("\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\tdata:param,\n");
      out.write("\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\t\t$(\"#followingList\").html('');\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t$(data).each((i,u)=>{\n");
      out.write("\t\t\t\t\t\tvar html = '';\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<div class='firstRow'>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/upload/profile/\"+u.profileRenamedFilename+\"' class='header-profile-circle'  width='40' height='40' />\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+u.profileUserId+\"' class='followerURL'>\"+u.profileUserNickname+\"</a>\";\n");
      out.write("\t\t\t\t\t\tif(u.profileUserType=='S'){\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/img/checkmark.png' alt='''  width='20' height='20'  />\";\n");
      out.write("\t\t\t\t\t\t}\t\t\n");
      out.write("\t\t\t\t\t\thtml+=\"&nbsp;<span class='followerIntro'>@\"+u.profileUserId+\"</span>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\thtml+=\"<div class='ub-btns'>\"\n");
      out.write("\t\t\t\t\t\t\tif(u.profileUserId != '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\tif(followLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-danger' class='followerBtn' style='margin-right:2px;' value='\"+u.profileUserId+\"' onclick='unfollower(this);'>Unfollow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse if(blockLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("' == '");
      out.print(mypage );
      out.write("' || blockedLoggedInList.includes(u.profileUserId)) return;\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' value='\"+u.profileUserId+\"' class='btn btn-light' onclick='unblocker(this);''>Unblock</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse {\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-success' value='\"+u.profileUserId+\"' onclick='follower(this);'>Follow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' class='btn btn-dark' value='\"+u.profileUserId+\"' onclick='blocker(this);'>Block</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}else if(u.profileUserId == '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\thtml+=\"</div>\";\t\n");
      out.write("\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$(\"#followingList\").append(html);\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t}else if($(this).attr('data-tab')=='tab3'){\n");
      out.write("\t\t\tvar param1 = {\n");
      out.write("\t\t\t\t\tuserLoggedIn : '");
      out.print(userLoggedIn.getUserId());
      out.write("',\n");
      out.write("\t\t\t\t\tmypage : '");
      out.print(mypage );
      out.write("'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif($(\"#tab3\").children().children(\".followList\").attr('id')=='followedList'){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\turl:\"");
      out.print(request.getContextPath() );
      out.write("/gson/sns/followedOneList.do\",\n");
      out.write("\t\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\t\tdata: param1,\n");
      out.write("\t\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t$(\"#followedList\").html('');\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$(data).each((i,u)=>{\n");
      out.write("\t\t\t\t\t\t\tvar html = '';\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='firstRow'>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/upload/profile/\"+u.profileRenamedFilename+\"' class='header-profile-circle'  width='40' height='40' />\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+u.profileUserId+\"' class='followerURL'>\"+u.profileUserNickname+\"</a>\";\n");
      out.write("\t\t\t\t\t\t\tif(u.profileUserType=='S'){\n");
      out.write("\t\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/img/checkmark.png' alt='''  width='20' height='20'  />\";\n");
      out.write("\t\t\t\t\t\t\t}\t\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"&nbsp;<span class='followerIntro'>@\"+u.profileUserId+\"</span>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='ub-btns'>\"\n");
      out.write("\t\t\t\t\t\t\tif(u.profileUserId != '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\tif(followLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-danger' class='followerBtn' style='margin-right:2px;' value='\"+u.profileUserId+\"' onclick='unfollower(this);'>Unfollow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse if(blockLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("' == '");
      out.print(mypage );
      out.write("' || blockedLoggedInList.includes(u.profileUserId)) return;\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' value='\"+u.profileUserId+\"' class='btn btn-light' onclick='unblocker(this);''>Unblock</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\telse {\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-success' value='\"+u.profileUserId+\"' onclick='follower(this);'>Follow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' class='btn btn-dark' value='\"+u.profileUserId+\"' onclick='blocker(this);'>Block</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}else if(u.profileUserId == '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\";\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$(\"#followedList\").append(html);\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t}else if($(\"#tab3\").children().children(\".followList\").attr('id')=='followerWithList'){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\turl:\"");
      out.print(request.getContextPath() );
      out.write("/gson/sns/followerWithList.do\",\n");
      out.write("\t\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\t\tdata:param1,\n");
      out.write("\t\t\t\t\tdataType:\"json\",\n");
      out.write("\t\t\t\t\tsuccess: function(data){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t$(\"#followerWithList\").html('');\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$(data).each((i,u)=>{\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\tvar html = '';\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='firstRow'>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/upload/profile/\"+u.profileRenamedFilename+\"' class='header-profile-circle'  width='40' height='40' />\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<a href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+u.profileUserId+\"' class='followerURL'>\"+u.profileUserNickname+\"</a>\";\n");
      out.write("\t\t\t\t\t\t\tif(u.profileUserType=='S'){\n");
      out.write("\t\t\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath() );
      out.write("/img/checkmark.png' alt='''  width='20' height='20'  />\";\n");
      out.write("\t\t\t\t\t\t\t}\t\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"&nbsp;<span class='followerIntro'>@\"+u.profileUserId+\"</span>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='ub-btns'>\"\n");
      out.write("\t\t\t\t\t\t\t\tif(u.profileUserId != '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\t\tif(followLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-danger' class='followerBtn' style='margin-right:2px;' value='\"+u.profileUserId+\"' onclick='unfollower(this);'>Unfollow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\telse if(blockLoggedInList.includes(u.profileUserId)){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("' == '");
      out.print(mypage );
      out.write("' || blockedLoggedInList.includes(u.profileUserId)) return;\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' value='\"+u.profileUserId+\"' class='btn btn-light' onclick='unblocker(this);''>Unblock</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\telse {\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='whiteArea' style='display:inline; margin-right:2px;'><button type='button' class='btn btn-success' value='\"+u.profileUserId+\"' onclick='follower(this);'>Follow</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+=\"<div class='darkArea' style='display:inline;'><button type='button' class='btn btn-dark' value='\"+u.profileUserId+\"' onclick='blocker(this);'>Block</button></div>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t}else if(u.profileUserId == '");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\";\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$(\"#followerWithList\").append(html);\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\t\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t})\n");
      out.write("});\n");
      out.write("\n");
      out.write("function unfollower(btn){\n");
      out.write("\tconsole.log($(btn).prop('value'));\n");
      out.write("\t\tvar param={\n");
      out.write("\t\t\tuserFollowing : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\n");
      out.write("\t\t\tuserFollowed : $(btn).val()\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/unFollow.do',\n");
      out.write("\t\t\tdata : param,\n");
      out.write("\t\t\tdataType: 'json',\n");
      out.write("\t\t\ttype : 'post',\n");
      out.write("\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tfollowLoggedInList.pop(followLoggedInList.indexOf($(btn).val()));\n");
      out.write("\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("'=='");
      out.print(mypage );
      out.write("'){\n");
      out.write("\t\t\t\t\t$(btn).parent().parent().parent().remove();\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(btn).parent().next().html(\"<button type='button' class='btn btn-dark' value='\"+$(btn).val()+\"' onclick='blocker(this);'>Block</button>\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(btn).removeClass(\"btn-danger\");\n");
      out.write("\t\t\t\t$(btn).addClass(\"btn-success\");\n");
      out.write("\t\t\t\t$(btn).html(\"Follow\");\n");
      out.write("\t\t\t\t$(btn).off('click');\n");
      out.write("\t\t\t\t$(btn).on('click', follower);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror : function(data){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tcomplete: function(data){\n");
      out.write("\t\t\t\tfollowLoggedInList.splice(followLoggedInList.indexOf($(btn).val),1);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}) \n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("function follower(btn){\n");
      out.write("\tconsole.log($(btn).prop('value'));\n");
      out.write("\tvar param={\n");
      out.write("\t\tuserFollowing : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\n");
      out.write("\t\tuserFollowed : $(btn).val()\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/follow.do',\n");
      out.write("\t\tdata : param,\n");
      out.write("\t\tdataType: 'json',\n");
      out.write("\t\ttype : 'post',\n");
      out.write("\t\tsuccess : function(data){\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfollowLoggedInList.push($(btn).val());\n");
      out.write("\n");
      out.write("\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("'=='");
      out.print(mypage );
      out.write("'){\n");
      out.write("\t\t\t\t$(btn).parent().parent().parent().remove();\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(btn).parent().next().html('');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(btn).removeClass(\"btn-success\");\n");
      out.write("\t\t\t$(btn).addClass(\"btn-danger\");\n");
      out.write("\t\t\t$(btn).html(\"Unfollow\");\n");
      out.write("\t\t\t$(btn).off('click')\n");
      out.write("\t\t\t$(btn).on('click', unfollower);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\terror : function(data){\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\n");
      out.write("\t\t},\n");
      out.write("\t\tcomplete: function(data){\n");
      out.write("\t\t\tfollowLoggedInList.push($(btn).val());\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t}) \n");
      out.write("\n");
      out.write("}\n");
      out.write("function blocker(btn){\n");
      out.write("\tconsole.log($(btn).prop('value'));\n");
      out.write("\tvar param={\n");
      out.write("\t\t\tuserBlocking : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\n");
      out.write("\t\t\tuserBlocked : $(btn).val()    \t\t\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/block.do',\n");
      out.write("\t\t\tdata : param,\n");
      out.write("\t\t\tdataType: 'json',\n");
      out.write("\t\t\ttype : 'post',\n");
      out.write("\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\t\tblockLoggedInList.push($(btn).val());\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif('");
      out.print(userLoggedIn.getUserId());
      out.write("'=='");
      out.print(mypage );
      out.write("'){\n");
      out.write("\t\t\t\t\t\t$(btn).parent().parent().parent().remove();\n");
      out.write("\t\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t$(btn).parent().prev().children().remove();\n");
      out.write("\t\t\t\t\t$(btn).removeClass(\"btn-dark\");\n");
      out.write("\t\t\t\t\t$(btn).addClass(\"btn-light\");\n");
      out.write("\t\t\t\t\t$(btn).text(\"Unblock\");\n");
      out.write("\t\t\t\t\t$(btn).css(\"width\", \"105px\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(btn).off(\"click\");\n");
      out.write("\t\t\t\t\t$(btn).on(\"click\", unblocker);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror : function(data){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tcomplete: function(data){\n");
      out.write("\t\t\t\tblockLoggedInList.push($(btn).val);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}) \n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("function unblocker(btn){\n");
      out.write("\tvar param={\n");
      out.write("\t\t\tuserBlocking : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\n");
      out.write("\t\t\tuserBlocked : $(btn).val()    \t\t\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/unblock.do',\n");
      out.write("\t\t\tdata : param,\n");
      out.write("\t\t\tdataType: 'json',\n");
      out.write("\t\t\ttype : 'post',\n");
      out.write("\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\tblockLoggedInList.pop(blockLoggedInList.IndexOf($(btn).val()));\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(btn).parent().prev().html(\"<button type='button' class='btn btn-success' value='\"+$(btn).val()+\"' onclick='follower(this);'>Follow</button>\");\n");
      out.write("\n");
      out.write("\t\t\t\t$(btn).removeClass(\"btn-light\");\n");
      out.write("\t\t\t\t$(btn).addClass(\"btn-dark\");\n");
      out.write("\t\t\t\t$(btn).text(\"block\");\n");
      out.write("\t\t\t\t$(btn).css(\"width\", \"81.36px\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(btn).off(\"click\");\n");
      out.write("\t\t\t\t$(btn).on(\"click\", blocker);\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror : function(data){\n");
      out.write("\t\t\t\tconsole.log(\"ajax처리실패\");\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tcomplete: function(data){\n");
      out.write("\t\t\t\tblockLoggedInList = [];\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}) \n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write(" <div id=\"follower-container\">\n");
      out.write(" <br>\n");
      out.write("<div id=\"followerSearch\">\n");
      out.write(" \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/magnifying-glass.png\" class=\"magni\" width='20' height='20'/>\n");
      out.write("\t\t\t<label for='followSearch' style='float:left; margin:0px 5px 0px 2px;'>전체 유저검색</label>\n");
      out.write("\t\t\t<input type=\"search\" name=\"followerSearch\" class=\"followerSearch\" id='followSearch'/>\n");
      out.write(" </div>\n");
      out.write(" \n");
      out.write(" <br><br>\n");
      out.write("\t\t\t<ul class=\"tab\">\n");
      out.write("\t\t\t");
if(userLoggedIn!=null && userLoggedIn.getUserId().equals(mypage)){ 
      out.write("\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab1\"><a>팔로우</a></li>\n");
      out.write("\t\t\t\t<li data-tab=\"tab2\"><a>팔로잉</a></li>\n");
      out.write("\t\t\t\t<li data-tab=\"tab3\"><a>나를 팔로잉한 사람</a></li>\n");
      out.write("\t\t\t");
 } else if(userLoggedIn!=null && !userLoggedIn.getUserId().equals(mypage)){
      out.write("\n");
      out.write("\t\t\t\t<li class=\"current\" data-tab=\"tab1\"><a>");
      out.print(mypageUser.getUsernickName() );
      out.write("의 팔로우</a></li>\n");
      out.write("\t\t\t\t<li data-tab=\"tab2\"><a>");
      out.print(mypageUser.getUsernickName() );
      out.write("의 팔로잉</a></li>\n");
      out.write("\t\t\t\t<li data-tab=\"tab3\"><a>함께 팔로우한 사람</a></li>\n");
      out.write("\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"tab1\" class=\"tabcontent current\">\n");
      out.write("\t\t\t\t<div class=\"followListContainer\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<table class=\"followList\" id=\"followerList\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"tab2\" class=\"tabcontent\">\n");
      out.write("\t\t\t\t<div class=\"followListContainer\">\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t<table class=\"followList\" id=\"followingList\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"tab3\" class=\"tabcontent\">\n");
      out.write("\t\t\t");
if(userLoggedIn!=null && userLoggedIn.getUserId().equals(mypage)){ 
      out.write("\n");
      out.write("\t\t\t\t<div class=\"followListContainer\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t<table class=\"followList\" id=\"followedList\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t    ");
 } else{
      out.write("\n");
      out.write("\t\t    \t<div class=\"followListContainer\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<table class=\"followList\" id=\"followerWithList\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t    \t</div>\n");
      out.write("\t\t   \t");
} 
      out.write("\n");
      out.write("\t\t    </div>\n");
      out.write("\n");
      out.write("\t\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
