/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-14 21:53:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;
import sns.model.vo.ProfileSNS;
import sns.model.vo.BoardSNS;
import sns.model.service.SNSService;
import java.util.List;

public final class myboardlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("sns.model.vo.BoardSNS");
    _jspx_imports_classes.add("user.model.vo.User");
    _jspx_imports_classes.add("sns.model.vo.ProfileSNS");
    _jspx_imports_classes.add("sns.model.service.SNSService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");

	String mypage = request.getParameter("mypage");
	int totalPage = Integer.parseInt(request.getParameter("totalPage"));
	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	

      out.write("\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("  <link href=\"/trav/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Custom fonts for this template -->\n");
      out.write("  <link href=\"/trav/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("  <!-- Custom styles for this template -->\n");
      out.write("  <link href=\"/trav/css/agency.min.css\" rel=\"stylesheet\">\n");
      out.write("  \n");
      out.write("  <!-- Bootstrap core JavaScript -->\n");
      out.write("  <script src=\"/trav/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"/trav/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Plugin JavaScript -->\n");
      out.write("  <script src=\"/trav/vendor/jquery-easing/jquery.easing.min.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Contact form JavaScript -->\n");
      out.write("  <script src=\"/trav/js/jqBootstrapValidation.js\"></script>\n");
      out.write("  <script src=\"/trav/js/contact_me.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Custom scripts for this template -->\n");
      out.write("  <script src=\"/trav/js/agency.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(()=>{\n");
      out.write("\tpageMore(1);\n");
      out.write("});\n");
      out.write("function unfollower(btn){\n");
      out.write("\tvar param={\n");
      out.write("\t\tuserFollowing : '");
      out.print(userLoggedIn.getUserId() );
      out.write("',\n");
      out.write("\t\tuserFollowed : $(btn).val()\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl : '");
      out.print(request.getContextPath());
      out.write("/gson/sns/unFollow.do',\n");
      out.write("\t\tdata : param,\n");
      out.write("\t\tdataType: 'json',\n");
      out.write("\t\ttype : 'post',\n");
      out.write("\t\tsuccess : function(data){\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(btn).parent().parent().parent().remove();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\terror : function(data){\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패\");\n");
      out.write("\t\t},\n");
      out.write("\t\tcomplete: function(data){\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t}) \n");
      out.write("\n");
      out.write("}\n");
      out.write("function pageMore(cPage){\n");
      out.write("\tvar param = {\n");
      out.write("\t\t\tcPage:cPage,\n");
      out.write("\t\t\tmypage:'");
      out.print(mypage );
      out.write("'\n");
      out.write("\t}\n");
      out.write("\t$.ajax({\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/gson/sns/myBoardSNSList.do\",\n");
      out.write("\t\tdata: param,\n");
      out.write("\t\ttype: \"get\",\n");
      out.write("\t\tdataType: \"json\",\n");
      out.write("\t\tsuccess: function(data){\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar html = \"\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$.each(data,(i,tl)=>{\n");
      out.write("\t\t\t\thtml+=\"<table class='tbl-boardsns'>\"\n");
      out.write("\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\thtml+=\"<td class='timeline-boardcontent-sns'>\";\n");
      out.write("\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/profile/\"+tl.profileSNS.profileRenamedFilename+\"' class='header-profile-circle' width='30' height='30' />\";\n");
      out.write("\t\t\t\thtml+=\"<span style='font-weight: 600'><a class='nickname-sns' href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+tl.boardSNS.boardWriter+\"'>\"+tl.profileSNS.userNickname+\"</a></span>\";\n");
      out.write("\t\t\t\thtml+=\"<span style='font-size: 0.8em; color: gray;''>\"+tl.boardSNS.boardDate+\"</span>\";\n");
      out.write("\t\t\t\thtml+=\"<span style='float: right;'>\";\n");
      out.write("\t\t\t\tif(tl.boardSNS.boardWriter!='");
      out.print(userLoggedIn.getUserId());
      out.write("'){\n");
      out.write("\t\t\t\t\thtml+=\"<button type='button' class='btn btn-danger' class='followerBtn' value='\"+tl.boardSNS.boardWriter+\"' onclick='unfollower(this);'>Unfollow</button>\";\n");
      out.write("\t\t\t\t\thtml+=\"&nbsp;\"\n");
      out.write("\t\t\t\t\thtml+=\"<button type='button' class='btn btn-dark'>Block</button>\";\n");
      out.write("\t\t\t\t} \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\thtml+=\"</span>\";\n");
      out.write("\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\tif(tl.imageSNSList!=null){\n");
      out.write("\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\thtml+=\"<td>\"\n");
      out.write("\t\t\t\t\thtml+=\"<div id='carouselExampleControls\"+tl.boardSNS.boardNo+\"' class='carousel slide' data-ride='carousel'>\";\n");
      out.write("\t\t\t\t\thtml+=\"<div class='carousel-inner'>\";\n");
      out.write("\t\t\t\t\tfor(j=0; j<tl.imageSNSList.length; j++){\n");
      out.write("\t\t\t\t\t\tif(j==0){\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='carousel-item active'>\";\n");
      out.write("\t\t\t\t\t\t} else if(j>0){\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='carousel-item'>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\thtml+=\"<img src='");
      out.print(request.getContextPath());
      out.write("/upload/board/\"+tl.imageSNSList[j].renamedFileName+\"' class='d-block w-100' alt='...'>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</div>\";\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\thtml+=\"</div>\";\n");
      out.write("\t\t\t\t\thtml+=\"<a class='carousel-control-prev' href='#carouselExampleControls\"+tl.boardSNS.boardNo+\"' role='button' data-slide='prev'>\";\n");
      out.write("\t\t\t\t\thtml+=\"<span class=;carousel-control-prev-icon' aria-hidden='true'></span>\"\n");
      out.write("\t\t\t\t\thtml+=\"<span class='sr-only'>Previous</span>\";\n");
      out.write("\t\t\t\t\thtml+=\"</a>\";\n");
      out.write("\t\t\t\t\thtml+=\"<a class='carousel-control-next' href='#carouselExampleControls\"+tl.boardSNS.boardNo+\"' role='button' data-slide='next'>\";\n");
      out.write("\t\t\t\t\thtml+=\"<span class='carousel-control-next-icon' aria-hidden='true'></span>\";\n");
      out.write("\t\t\t\t\thtml+=\"<span class='sr-only'>Next</span>\";\n");
      out.write("\t\t\t\t\thtml+=\"</a>\";\n");
      out.write("\t\t\t\t\thtml+=\"</div>\";\n");
      out.write("\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(tl.gradeSNSList!=null){\n");
      out.write("\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\thtml+=\"<table>\";\n");
      out.write("\t\t\t\t\thtml+=\"<tr>\"\n");
      out.write("\t\t\t\t\tfor(k=0; k<tl.gradeSNSList.length; k++){\n");
      out.write("\t\t\t\t\t\thtml+=\"<td class='tbl-td'>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"<div class='card h-100'>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<a href='#' class='goInfo'>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<img class='card-img-top' src='\"+tl.gradeSNSList[k].contentThumbnail+\"'></a>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='caption'>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='caption-text' ><a href='");
      out.print(request.getContextPath());
      out.write("/travel/detailPage?contentId=\"+tl.gradeSNSList[k].contentId+\"&contentTypeId=\"+tl.gradeSNSList[k].contentType+\"' target='_blank'>\"+tl.gradeSNSList[k].contentTitle+\"</a>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='contentid' style='display:none'>\"+tl.gradeSNSList[k].contentId+\"</div></h4>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<p class='card-text'>\"+tl.gradeSNSList[k].contentAddress+\"</p>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\"\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\thtml+=\"<div class='starRev'>\"\n");
      out.write("\t\t\t\t\t\t\t\tfor(var l=0; l<tl.gradeSNSList[k].grade; l++){\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<span class='starR on'>별</span>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\tfor(var m=0; m<5-tl.gradeSNSList[k].grade; m++){\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+=\"<span class='starR'>별</span>\";\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</div>\";\n");
      out.write("\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</table>\";\n");
      out.write("\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t}\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif(tl.boardSNS.boardContent!=null){\n");
      out.write("\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\thtml+=\"<td class='timeline-boardcontent-sns' style='text-align:left; padding: 10px; margin:10px;'><a class='nickname-sns' href='");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=\"+tl.boardSNS.boardWriter+\"'>@\"+tl.boardSNS.boardWriter+\"</a>&nbsp;\"+tl.boardSNS.boardContent+\"</td>\";\n");
      out.write("\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\thtml+=\"<t>\";\n");
      out.write("\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\thtml+=\"<span style='float: right; margin:10px;' ><img src='");
      out.print(request.getContextPath() );
      out.write("/img/beforelike.png' alt='' style='padding-top:2px; padding-bottom:-2px; width: 20px; height:20px'/>1&nbsp;&nbsp;<img src='");
      out.print(request.getContextPath() );
      out.write("/img/alarm.png' alt='' style='width: 20px; height:20px'/></span>\";\n");
      out.write("\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\thtml+=\"<td class='timeline-boardcontent-sns' >댓글(3)</td>\";\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\thtml+=\"<td class='timeline-boardcontent-sns'>\";\n");
      out.write("\t\t\t\thtml+=\"<span class='nick_sns'>@abcde</span>&nbsp;\";\n");
      out.write("\t\t\t\thtml+=\"<span style='float:right;'>좋아요&nbsp;&nbsp;신고</span>\";\n");
      out.write("\t\t\t\thtml+=\"</td>\";\t\t\n");
      out.write("\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\thtml+=\"</table>\"\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\tif(");
      out.print(totalPage);
      out.write(" >0){\n");
      out.write("\t\t\t\thtml+=\"<div id='trMore'>&nbsp;</div>\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t$(\"#myBoardList\").append(html);\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t$(\"#trMore\").click(function(e){\n");
      out.write("\t\t\tvar nextPage = Number($(e.target).val()) + 1;\n");
      out.write("\t\t\tpageMore(nextPage);\n");
      out.write("\t\t\t$(this).remove();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//cPage값을 #btn-more에 저장하기\n");
      out.write("\t\t$(\"#trMore\").val(cPage).text(\"더보기(\"+cPage+\"/");
      out.print(totalPage );
      out.write(")\");\n");
      out.write("\t\t\n");
      out.write("\t\t//마지막 페이지인 경우, 더보기 버튼 비활성화\n");
      out.write("\t\tif(cPage == ");
      out.print(totalPage);
      out.write("){\n");
      out.write("\t\t\t$(\"#trMore\").remove();\n");
      out.write("\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t},\n");
      out.write("\t\terror: function(jqxhr, textStatus, errorThrown){\n");
      out.write("\t\t\tconsole.log(\"ajax처리실패!\");\n");
      out.write("\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\t\n");
      out.write("\t<style>#tdMore{text-align:center; padding: 10px; cursor:pointer; }\n");
      out.write("\n");
      out.write(".w-100{\n");
      out.write(" \twidth:532px;\n");
      out.write(" \theight:532px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".timeline-boardcontent-sns{\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("}\n");
      out.write(".wrapper{\n");
      out.write("\tposition:relative;\n");
      out.write("}\n");
      out.write("#autoComplete{\n");
      out.write("\tdisplay: none;\n");
      out.write("\tbackground: white;\n");
      out.write("\tmin-width: 253px;\n");
      out.write("\tborder: 1px solid gray;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 22px;\n");
      out.write("\tleft: 0px;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin: 0;\n");
      out.write("}\n");
      out.write("#autoComplete li{\n");
      out.write("\tpadding: 0 10px;\n");
      out.write("\tlist-style: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("#autoComplete li.sel{\n");
      out.write("\tbackground: gray;\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search{\n");
      out.write("\tmargin-bottom: 5px;\n");
      out.write("}\n");
      out.write("#searchFrm{\n");
      out.write("\tdisplay: inline;\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write(".row{\n");
      out.write("padding: 0 10px;\n");
      out.write("text-align: center;\n");
      out.write("}\n");
      out.write(".row .card-img-top, .goInfo{\n");
      out.write("width: 150px; height:  150px;\n");
      out.write("position: relative;\n");
      out.write("}\n");
      out.write(".card-img-top{\n");
      out.write("\tborder:1px solid gray;\n");
      out.write("\twidth: 150px;\n");
      out.write("\theight: 150px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".h-100{\n");
      out.write("width: 150px;\n");
      out.write("border: 1px solid transparent;\n");
      out.write("padding: 0 2px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card-text{\n");
      out.write("\tfont-size: 0.8em;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.caption{\n");
      out.write("\tdisplay:block;\n");
      out.write("\twidth: 150px; height: 150px;\n");
      out.write("\tposition: absolute;\n");
      out.write("    top:0px;\n");
      out.write("    padding: 0px;\n");
      out.write("    opacity: 0; \n");
      out.write("    background: rgb(0, 0, 0, 0.5);\n");
      out.write("    cursor: pointer;   \n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".h-100:hover .caption{\n");
      out.write("\topacity: 1;\n");
      out.write("}\n");
      out.write("p.card-text{\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write(".row{\n");
      out.write("\tdisplay: table;\n");
      out.write("}\n");
      out.write(".row div{\n");
      out.write("    display: table-cell;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".caption-text{\n");
      out.write("\twidth: 150px;\n");
      out.write("\theight: 150px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tdisplay:table-cell;\n");
      out.write("\tvertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cc{\n");
      out.write("\tposition: absolute;\n");
      out.write("\tcolor:#fec503;\n");
      out.write("\ttop:1px;\n");
      out.write("\tleft:135px;\n");
      out.write("\tcurser:pointer;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write(".starR{\n");
      out.write("  background: url('http://miuu227.godohosting.com/images/icon/ico_review.png') no-repeat right 0;\n");
      out.write("  background-size: auto 100%;\n");
      out.write("  width: 30px;\n");
      out.write("  height: 30px;\n");
      out.write("  display:table-cell;\n");
      out.write("  text-indent: -9999px;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write(".starR.on{background-position:0 0;}\n");
      out.write("\n");
      out.write(".starRev{\n");
      out.write("\tmargin:0 auto;\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".tbl-td {\n");
      out.write("\twidth: 173px; height: 173px; \n");
      out.write("}\n");
      out.write(".tbl-td .card-img-top, .goInfo {\n");
      out.write("\twidth: 173px; height: 173px; position: relative;\n");
      out.write("}\n");
      out.write(".tbl-td .card-img-top{\n");
      out.write("\tborder: 1px black solid;\n");
      out.write("\twidth: 173px;\n");
      out.write("\theight: 173px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write(".tbl-td .h-100{\n");
      out.write("\twidth: 174px;\n");
      out.write("\t\n");
      out.write("\tpadding: 0;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("\t\n");
      out.write(".tbl-td\tdiv.caption{\n");
      out.write("\t\tdisplay:block;\n");
      out.write("\t\twidth: 173px; height: 173px;\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t    top:0px;\n");
      out.write("\t    padding: 0px;\n");
      out.write("\t    opacity: 0; \n");
      out.write("\t    background: rgb(0, 0, 0, 0.5);\n");
      out.write("\t    cursor: pointer;   \n");
      out.write("\t    text-align: center;\n");
      out.write("\t    vertical-align: middle;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write(".tbl-td\t.h-100:hover .caption{\n");
      out.write("\t\topacity: 1;\n");
      out.write("\t}\n");
      out.write(".tbl-td\tp.card-text{\n");
      out.write("\t\tcolor: white;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write(".tbl-td .card-text, a{\n");
      out.write("\tfont-size: 1em;\n");
      out.write("}\n");
      out.write("\t\n");
      out.write(".tbl-td\t.caption-text{\n");
      out.write("\t\twidth: 173px;\n");
      out.write("\t\theight: 173px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tdisplay:table-cell;\n");
      out.write("\t\tvertical-align: middle;\n");
      out.write("\t}\n");
      out.write(".tbl-td\t.starR{\n");
      out.write("\tbackground: url('http://miuu227.godohosting.com/images/icon/ico_review.png') no-repeat right 0;\n");
      out.write("\tbackground-size: auto 100%;\n");
      out.write("\twidth: 30px;\n");
      out.write("\theight: 30px;\n");
      out.write("\tdisplay:table-cell;\n");
      out.write("\ttext-indent: -9999px;\n");
      out.write("\tcursor:none;\n");
      out.write("\t\t  \n");
      out.write("}\n");
      out.write(".tbl-td\t.starR.on{background-position:0 0;}\n");
      out.write("\t\t\n");
      out.write(".tbl-td\t.starRev{\n");
      out.write("\tmargin:0 auto;\n");
      out.write("\twidth:150px;\n");
      out.write("\tmarign:0 auto;\n");
      out.write("}\t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write(".tbl-boardsns{\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nickname-sns{\n");
      out.write("\tfont-size:1.2em;\n");
      out.write("\tfont-weight: 700;\n");
      out.write("\tcolor:black;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("#trMore{\n");
      out.write("\tcursor:pointer;\n");
      out.write("\tpadding-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<div class=\"timeline-board-sns\" id=\"myBoardList\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
