/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-15 14:13:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.service.UserService;
import sns.model.vo.ProfileSNS;
import sns.model.service.SNSService;
import user.model.vo.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/common/header-menu.jsp", Long.valueOf(1565878183000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.service.UserService");
    _jspx_imports_classes.add("sns.model.vo.ProfileSNS");
    _jspx_imports_classes.add("sns.model.service.SNSService");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write(" <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"/trav/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"/trav/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"/trav/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"/trav/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"/trav/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"/trav/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"/trav/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"/trav/js/contact_me.js\"></script>\r\n");
      out.write("  <!-- Custom scripts for this template -->\r\n");
      out.write("  <script src=\"/trav/js/agency.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");


	User userLoggedIn = (User)session.getAttribute("userLoggedIn");
	System.out.println("userLoggedIn@userLogin.jsp=" + userLoggedIn);
	User loggedIn = null;
	if(userLoggedIn!=null){
		loggedIn = new UserService().selectOne(userLoggedIn.getUserId());
	}

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <title>유람</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("header.masthead{\r\n");
      out.write("background-image:url(");
      out.print(request.getContextPath());
      out.write("/img/header-new.jpg);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".header-profile-circle{\r\n");
      out.write("    border: 0px;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-menu-container{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/\">유람</a>\r\n");
      out.write("      <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        Menu\r\n");
      out.write("        <i class=\"fas fa-bars\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("        <ul class=\"navbar-nav text-uppercase ml-auto\">\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/travel/travelSelectArea\">여행지</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("\t\t  <li class=\"nav-item\">\r\n");
      out.write("\t\t  ");
 if(userLoggedIn!=null){
      out.write("\r\n");
      out.write("\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain?mypage=");
      out.print(userLoggedIn.getUserId() );
      out.write("\">여행이야기</a>\r\n");
      out.write("\t      ");
} else{ 
      out.write("\r\n");
      out.write("\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/story/storyMain\">여행이야기</a>\r\n");
      out.write("\t      ");
} 
      out.write("\r\n");
      out.write("\t      \r\n");
      out.write("\t      </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <span class=\"nav-link js-scroll-trigger\">&nbsp;&nbsp;</span>\r\n");
      out.write("          </li>\r\n");
      out.write("         ");
if(userLoggedIn==null){ 
      out.write("\r\n");
      out.write("\t          <li class=\"nav-item\">\r\n");
      out.write("\t            <a class=\"nav-link js-scroll-trigger\" href='");
      out.print(request.getContextPath() );
      out.write("/user/userLoginFrm'>로그인</a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t          </li> \r\n");
      out.write("\t\t      <li class=\"nav-item\">\r\n");
      out.write("\t\t        <a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath());
      out.write("/user/userEnrollFrm\">회원가입</a>\r\n");
      out.write("\t\t      </li>\r\n");
      out.write("         ");
 }
          	else if(userLoggedIn!=null && "A".equals(userLoggedIn.getUserType())){
      out.write("\r\n");
      out.write("          \t<li class=\"nav-item\">\r\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/user/userLogout\">로그아웃</a>\r\n");
      out.write("         \t</li>\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/admin/adminView'>\r\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/이동욱.jpg\" class=\"header-profile-circle\"  width=\"40\" height=\"40\" />\r\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t         </li> \r\n");
      out.write("          ");
 }
          	else if(userLoggedIn!=null){ 
      out.write("\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("            \t<a class=\"nav-link js-scroll-trigger\" href=\"");
      out.print(request.getContextPath() );
      out.write("/user/userLogout\">로그아웃</a>\r\n");
      out.write("         \t</li>\r\n");
      out.write("          \t <li class=\"nav-item\">\r\n");
      out.write("\t           <a class=\"nav-link js-scroll-trigger\" style=\"padding-top: 5px !important\" href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'>\r\n");
      out.write("\t           \t");
if(userLoggedIn==null || userLoggedIn.getFileName()==null){
      out.write("\r\n");
      out.write("\t           \t\t<button onclick=\"location.href='");
      out.print(request.getContextPath() );
      out.write("/mypage/mypageView'\"></button>\r\n");
      out.write("\t           \t");
 } else if(userLoggedIn!=null && loggedIn!=null) {
      out.write("\r\n");
      out.write("\t           \t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/profile/");
      out.print(loggedIn.getFileName() );
      out.write("\" class=\"header-profile-circle\"  width=\"40\" height=\"40\" />\r\n");
      out.write("\t           \t");
} 
      out.write("\r\n");
      out.write("\t           </a> <!-- userLogin.jsp로 이동하는 서블릿 -->\r\n");
      out.write("\t         </li> \r\n");
      out.write("         ");
} 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath() );
      out.write("/css/agency.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Plugin JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Contact form JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/contact_me.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom scripts for this template -->\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/agency.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write(" \tfunction searchGo(e){\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\tif(e.key==\"Enter\"){\r\n");
      out.write(" \t\t\tvar sido1=\"\";\r\n");
      out.write(" \t\t\tvar gugun1=\"\";\r\n");
      out.write(" \t\t\tvar area1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\tfor(var i=0;i<area1.length;i++){\r\n");
      out.write(" \t\t\t\tif(area1[i]==$(\"#searchKwd\").val()){\r\n");
      out.write(" \t\t\t\t\tsido1=1;\r\n");
      out.write(" \t\t\t\t\tgugun1=i+1;\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\tlocation.href=\"");
      out.print(request.getContextPath() );
      out.write("/travel/travelView?sido1=\"+sido1+\"&gugun1=\"+gugun1;\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t}\r\n");
      out.write("  </script>\r\n");
      out.write(" \r\n");
      out.write("   <!-- Header -->\r\n");
      out.write("  <header class=\"masthead\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"intro-text\">\r\n");
      out.write("        <div class=\"intro-heading text-uppercase\">지금 다양한 국내 여행지를 검색하세요.</div>\r\n");
      out.write("         <input type=\"search\" size=\"50\" style=\"height:50px;\" placeholder=\"찾으시는 구/군을 입력해주세요.\" id=\"searchKwd\" onkeyup=\"searchGo(event);\"/>\r\n");
      out.write("       \t\t<br>\r\n");
      out.write("       \t <span class=\"intro-lead-in\">7월의 추천검색어 : <a href='#' style='color: orangered'>#해운대</a> <a href='#' style='color: orangered'>#강릉</a>  <a href='#' style='color: orangered'>#정선</a></span>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- Services -->\r\n");
      out.write("  <section class=\"page-section\" id=\"services\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading text-uppercase\">7월의 여행테마 : 여름 바캉스</h2>\r\n");
      out.write("          <h3 class=\"section-subheading text-muted\" style=\"margin-bottom:100px;\">무더위를 피해 \r\n");
      out.write("          \t<a href='#' style='color: orangered'>#해운대</a> \r\n");
      out.write("          \t<a href='#' style='color: orangered'>#강릉</a> \r\n");
      out.write("          \t<a href='#' style='color: orangered'>#정선</a>으로 떠나요!</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row text-center\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"fa-stack fa-4x\">\r\n");
      out.write("            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("            <i class=\"fas fa-shopping-cart fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("          <h4 class=\"service-heading\">E-Commerce</h4>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"fa-stack fa-4x\">\r\n");
      out.write("            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("            <i class=\"fas fa-laptop fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("          <h4 class=\"service-heading\">Responsive Design</h4>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"fa-stack fa-4x\">\r\n");
      out.write("            <i class=\"fas fa-circle fa-stack-2x text-primary\"></i>\r\n");
      out.write("            <i class=\"fas fa-lock fa-stack-1x fa-inverse\"></i>\r\n");
      out.write("          </span>\r\n");
      out.write("          <h4 class=\"service-heading\">Web Security</h4>\r\n");
      out.write("          <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- Portfolio Grid -->\r\n");
      out.write("  <section class=\"bg-light page-section\" id=\"portfolio\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading text-uppercase\">인기 여행지 Top10</h2>\r\n");
      out.write("          <h3 class=\"section-subheading text-muted\" style=\"margin-bottom:100px;\">인기 여행지를 한눈에!</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal1\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/01-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Threads</h4>\r\n");
      out.write("            <p class=\"text-muted\">Illustration</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal2\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/02-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Explore</h4>\r\n");
      out.write("            <p class=\"text-muted\">Graphic Design</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal3\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/03-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Finish</h4>\r\n");
      out.write("            <p class=\"text-muted\">Identity</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal4\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/04-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Lines</h4>\r\n");
      out.write("            <p class=\"text-muted\">Branding</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal5\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/05-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Southwest</h4>\r\n");
      out.write("            <p class=\"text-muted\">Website Design</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4 col-sm-6 portfolio-item\">\r\n");
      out.write("          <a class=\"portfolio-link\" data-toggle=\"modal\" href=\"#portfolioModal6\">\r\n");
      out.write("            <div class=\"portfolio-hover\">\r\n");
      out.write("              <div class=\"portfolio-hover-content\">\r\n");
      out.write("                <i class=\"fas fa-plus fa-3x\"></i>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img class=\"img-fluid\" src=\"img/portfolio/06-thumbnail.jpg\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"portfolio-caption\">\r\n");
      out.write("            <h4>Window</h4>\r\n");
      out.write("            <p class=\"text-muted\">Photography</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- About\r\n");
      out.write("  <section class=\"page-section\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading text-uppercase\">About</h2>\r\n");
      out.write("          <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <ul class=\"timeline\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <div class=\"timeline-image\">\r\n");
      out.write("                <img class=\"rounded-circle img-fluid\" src=\"img/about/1.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"timeline-panel\">\r\n");
      out.write("                <div class=\"timeline-heading\">\r\n");
      out.write("                  <h4>2009-2011</h4>\r\n");
      out.write("                  <h4 class=\"subheading\">Our Humble Beginnings</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timeline-body\">\r\n");
      out.write("                  <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"timeline-inverted\">\r\n");
      out.write("              <div class=\"timeline-image\">\r\n");
      out.write("                <img class=\"rounded-circle img-fluid\" src=\"img/about/2.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"timeline-panel\">\r\n");
      out.write("                <div class=\"timeline-heading\">\r\n");
      out.write("                  <h4>March 2011</h4>\r\n");
      out.write("                  <h4 class=\"subheading\">An Agency is Born</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timeline-body\">\r\n");
      out.write("                  <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <div class=\"timeline-image\">\r\n");
      out.write("                <img class=\"rounded-circle img-fluid\" src=\"img/about/3.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"timeline-panel\">\r\n");
      out.write("                <div class=\"timeline-heading\">\r\n");
      out.write("                  <h4>December 2012</h4>\r\n");
      out.write("                  <h4 class=\"subheading\">Transition to Full Service</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timeline-body\">\r\n");
      out.write("                  <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"timeline-inverted\">\r\n");
      out.write("              <div class=\"timeline-image\">\r\n");
      out.write("                <img class=\"rounded-circle img-fluid\" src=\"img/about/4.jpg\" alt=\"\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"timeline-panel\">\r\n");
      out.write("                <div class=\"timeline-heading\">\r\n");
      out.write("                  <h4>July 2014</h4>\r\n");
      out.write("                  <h4 class=\"subheading\">Phase Two Expansion</h4>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"timeline-body\">\r\n");
      out.write("                  <p class=\"text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"timeline-inverted\">\r\n");
      out.write("              <div class=\"timeline-image\">\r\n");
      out.write("                <h4>Be Part\r\n");
      out.write("                  <br>Of Our\r\n");
      out.write("                  <br>Story!</h4>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write(" -->\r\n");
      out.write("  <!-- Team -->\r\n");
      out.write("  <section class=\"bg-light page-section\" id=\"team\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading text-uppercase\">실시간 여행이야기</h2>\r\n");
      out.write("          <h3 class=\"section-subheading text-muted\" style=\"margin-bottom:100px;\"><a href='#' style=\"color: orangered;\">로그인</a>해서 당신의 여행이야기를 들려주세요.</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("          <div class=\"team-member\">\r\n");
      out.write("            <img class=\"mx-auto rounded-circle\" src=\"img/team/1.jpg\" alt=\"\">\r\n");
      out.write("            <h4>Kay Garland</h4>\r\n");
      out.write("            <p class=\"text-muted\">Lead Designer</p>\r\n");
      out.write("            <ul class=\"list-inline social-buttons\">\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("          <div class=\"team-member\">\r\n");
      out.write("            <img class=\"mx-auto rounded-circle\" src=\"img/team/2.jpg\" alt=\"\">\r\n");
      out.write("            <h4>Larry Parker</h4>\r\n");
      out.write("            <p class=\"text-muted\">Lead Marketer</p>\r\n");
      out.write("            <ul class=\"list-inline social-buttons\">\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("          <div class=\"team-member\">\r\n");
      out.write("            <img class=\"mx-auto rounded-circle\" src=\"img/team/3.jpg\" alt=\"\">\r\n");
      out.write("            <h4>Diana Pertersen</h4>\r\n");
      out.write("            <p class=\"text-muted\">Lead Developer</p>\r\n");
      out.write("            <ul class=\"list-inline social-buttons\">\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"list-inline-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-8 mx-auto text-center\">\r\n");
      out.write("          <p class=\"large text-muted\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Contact -->\r\n");
      out.write("  <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("          <h2 class=\"section-heading text-uppercase\">Contact Us</h2>\r\n");
      out.write("          <h3 class=\"section-subheading text-muted\">Lorem ipsum dolor sit amet consectetur.</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("          <form id=\"contactForm\" name=\"sentMessage\" novalidate=\"novalidate\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Your Name *\" required=\"required\" data-validation-required-message=\"Please enter your name.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Your Email *\" required=\"required\" data-validation-required-message=\"Please enter your email address.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Your Phone *\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\">\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <textarea class=\"form-control\" id=\"message\" placeholder=\"Your Message *\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\r\n");
      out.write("                  <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                <div id=\"success\"></div>\r\n");
      out.write("                <button id=\"sendMessageButton\" class=\"btn btn-primary btn-xl text-uppercase\" type=\"submit\">Send Message</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row align-items-center\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"copyright\">Copyright &copy; Your Website 2019</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline social-buttons\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">\r\n");
      out.write("                <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline quicklinks\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">Terms of Use</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Portfolio Modals -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 1 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/01-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Threads</li>\r\n");
      out.write("                  <li>Category: Illustration</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 2 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/02-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Explore</li>\r\n");
      out.write("                  <li>Category: Graphic Design</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 3 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/03-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Finish</li>\r\n");
      out.write("                  <li>Category: Identity</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 4 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/04-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Lines</li>\r\n");
      out.write("                  <li>Category: Branding</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 5 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/05-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Southwest</li>\r\n");
      out.write("                  <li>Category: Website Design</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Modal 6 -->\r\n");
      out.write("  <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"close-modal\" data-dismiss=\"modal\">\r\n");
      out.write("          <div class=\"lr\">\r\n");
      out.write("            <div class=\"rl\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <!-- Project Details Go Here -->\r\n");
      out.write("                <h2 class=\"text-uppercase\">Project Name</h2>\r\n");
      out.write("                <p class=\"item-intro text-muted\">Lorem ipsum dolor sit amet consectetur.</p>\r\n");
      out.write("                <img class=\"img-fluid d-block mx-auto\" src=\"img/portfolio/06-full.jpg\" alt=\"\">\r\n");
      out.write("                <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>\r\n");
      out.write("                <ul class=\"list-inline\">\r\n");
      out.write("                  <li>Date: January 2017</li>\r\n");
      out.write("                  <li>Client: Window</li>\r\n");
      out.write("                  <li>Category: Photography</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <button class=\"btn btn-primary\" data-dismiss=\"modal\" type=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                  Close Project</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
